### ISSUE TITLE
Add tailwind demos

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/website#540]
We want to add Tailwind demos alongside CSS and Stitches.

- [x] Accordion @joaom00  #557 
- [x] Alert Dialog @shadcn #603 
- [x] Aspect Ratio @shadcn #579 
- [x] Avatar @shadcn #580
- [x] Checkbox @shadcn #577
- [x] Collapsible @ryanleichty #595 
- [x] Context Menu @ryanleichty #593 
- [x] Dialog @shadcn @shadcn #602 
- [x] Dropdown Menu @ryanleichty #592 
- [x] Hover Card @shadcn #578
- [x] Label @shadcn #581
- [x] Menubar @ryanleichty #594 
- [x] Navigation Menu @shadcn #604
- [x] Popover @joaom00 #576 
- [x] Progress @joaom00 #582 
- [x] Radio Group @joaom00 #583 
- [x] Scroll Area @joaom00 #584 
- [x] Select @ryanleichty #585 
- [x] Separator @joaom00 #586 
- [x] Slider @joaom00 #587 
- [x] Switch @joaom00 #588 
- [x] Tabs @joaom00 #589 
- [x] Toast @ryanleichty #596 
- [x] Toggle @suliskh #590
- [x] Toggle Group @suliskh #591 
- [x] Toolbar @ryanleichty #599
- [x] Tooltip @shadcn #601

**Comment by romansndlr** [comment]
Yes! We use Radix UI for our design system at Venn and we want to help! Since we use Tailwind this can be a great way for us to give back. How do we start?

**Comment by benoitgrelard** [comment]
Hey Roman, that's amazing! What a great way to give back! 🥰

Here are a few things to consider:
- One thing we're unsure how we'll achieve is how to closely match the Tailwind demos to what we currently have
  - spacing/colors might differ from the values we used in the demos (we use a 5px scale)
  - when we use icons, our icons have been designed at 15px (so fit nicely with our 5px scale)
- Perhaps we can find a way to include a customised tailwind config that matches?
- Or perhaps it's a better experience for users to see an out of the box Tailwind config, and it doesn't matter that the colors/size might look a tiny bit different

---

Perhaps a good starting point would be to do a **POC with one of the primitives**. Would you like to pick one and run with it?

I think roughly this is what it would involve:
- Add `tailwind` as a CSS lib in https://github.com/radix-ui/website/blob/main/lib/constants.ts
- Pick one primitive to do a POC for and create a new `tailwind` folder under it (for example: https://github.com/radix-ui/website/tree/main/components/demos/Accordion)
- Create the new tailwind demo in a new `index.jsx` file

The `HeroCodeBlock` stuff should mostly work out of the box with these changes, the only thing that will probably need changing is extra dependency/setup for the Codesandbox export for when the lib is tailwind: https://github.com/radix-ui/website/blob/47d4da7ba1d4459924e3958b09b9780fe3780c78/components/HeroCodeBlock.tsx#L302-L316)

Let me know if that's something you're able to run with, and thanks again for volunteering! 🙏

**Comment by benoitgrelard** [comment]
That could work, although I think ideally we would like to be as idiomatic as possible with how Tailwind is used.
Although arbitrary values are possible, that isn't typically how people would use Tailwind.

Go for it though if you want to try a POC though!
I know @romansndlr wanted to help too but it looks like he might not have had the time to do so yet.

**Comment by ryanleichty** [comment]
Are you still looking for help here? Would love to contribute 🙏🏻

**Comment by joaom00** [comment]
@ryanleichty I made a POC to see which direction to go. You can see here #557

**Comment by Rawnly** [comment]
If this can help somehow have a look at: https://ui.shadcn.com by @shadcn 😉

**Comment by joaom00** [comment]
@benoitgrelard I'm going from the middle to the bottom, so I'm going to start with popover

**Comment by suliskh** [comment]
Great works! 
I would be very happy if I can contribute @benoitgrelard @joaom00

**Comment by ryanleichty** [comment]
@benoitgrelard I can grab the select component if you want to assign me to it

**Comment by benoitgrelard** [comment]
@shadcn, @ryanleichty, done!
Thanks for stepping in and helping!

**Comment by shadcn** [comment]
@benoitgrelard How do we make it easy for you to QA? Attach codesandbox link to PRs?

**Comment by benoitgrelard** [comment]
The codesandbox is automatic, so in fact, that's what you'll test again yourself.
Have a look at the Accordion demo @joaom00 built, that should be a good example on how to do it.

**Comment by benoitgrelard** [comment]
When you're developing locally, choose Tailwind CSS in the dropdown there, and then click on the sandbox icon to see your live sandbox based on the files you work on locally.

![CleanShot 2023-02-09 at 17 17 57@2x](https://user-images.githubusercontent.com/1539897/217889163-e1d31f24-49e7-42ca-81e5-87918d13c289.png)

**Comment by shadcn** [comment]
> The codesandbox is automatic, so in fact, that's what you'll test again yourself.

Yep. This is how I'm testing.

**Comment by benoitgrelard** [comment]
Perfect, the PR builds previews automatically so we can check from there 👍

**Comment by shadcn** [comment]
@benoitgrelard PRs opened for `Checkbox` and `HoverCard`. 

Can you also assign me `AspectRatio`, `Avatar`, `Dialog` and `Label` please?

**Comment by joaom00** [comment]
Can also assign me `Progress`, `Radio Group` and `Scroll Area`

**Comment by suliskh** [comment]
I'll pick up `Toggle` and `Toggle Group` @benoitgrelard. Thanks!

**Comment by ryanleichty** [comment]
I created a pull request for the Select component #585

You can assign me `Collapsible`, `Dropdown Menu`, and `Toast`

**Comment by joaom00** [comment]
Now I'll pick `Separator`, `Slider`, `Switch`, `Tabs`

**Comment by benoitgrelard** [comment]
@suliskh done!

@ryanleichty done, also assigned `ContextMenu` and `Menubar` to you as if they are all very close to `DropdownMenu` so makes sense for the same person to tackle them.

@joaom00 done!

You guys are killing it! Thanks a bunch 🙏

**Comment by shadcn** [comment]
@benoitgrelard Assign me the remaining ones. I'm doing `Dialog`. I can get `Alert Dialog` as well.

I can do `Toolbar` and `Tooltip` if @joaom00 has not started on those yet.

**Comment by benoitgrelard** [comment]
@shadcn done!

Thanks!

**Comment by benoitgrelard** [comment]
Hey @shadcn, just checking if you still have bandwidth for the last few that were assigned to you?

**Comment by benoitgrelard** [comment]
No not blocked! No rush really, I just wanted to check in case someone else wanted to pick up. Thanks for the helping hand!

**Comment by shadcn** [comment]
The only one I’ve not started on is `Toolbar`. So if anyone wants to pick it up go ahead (let me know if you do). 

The rest are almost done.

**Comment by ryanleichty** [comment]
@shadcn I can work on the `Toolbar` right now 👍🏻

**Comment by shadcn** [comment]
@benoitgrelard Pushed PRs for `Alert Dialog`, `Dialog` and `Tooltip`. Now working on `Navigation Menu`.

- https://github.com/radix-ui/website/pull/603
- https://github.com/radix-ui/website/pull/602
- https://github.com/radix-ui/website/pull/601

**Comment by shadcn** [comment]
@benoitgrelard `Navigation Menu` is up https://github.com/radix-ui/website/pull/604

**Comment by benoitgrelard** [comment]
Sorry @shadcn I was off sick for a couple days, will take a look today!

**Comment by benoitgrelard** [comment]
This is now complete and shipped! 🚀 

A million thanks to @joaom00, @ryanleichty, @suliskh and @shadcn for pushing this through, you guys rock! 🤘
